services:

    rs_queue.redis_factory:
        class: RSQueue\RedisFactory
        arguments:
            - "%rs_queue.server.redis%"

    rs_queue.redis:
        class: StdObject
        factory:
            - "@rs_queue.redis_factory"
            - create