services:

    rs_queue.serializer.factory:
        class: RSQueue\Factory\SerializerFactory
        arguments:
            - "%rs_queue.serializer.class%"

    rs_queue.serializer:
        class: RSQueue\SerializerInterface