services:

    rs_queue.serializer.factory:
        class: RSQueue\Serializer\SerializerFactory
        arguments:
            - "%rs_queue.serializer.class%"

    rs_queue.serializer:
        class: RSQueue\Serializer\Serializer
        factory:
            - "@rs_queue.serializer.factory"
            - "create"