services:

    rs_queue.resolver.queuealias:
        class: Mmoreram\RSQueue\Resolver\QueueAliasResolver
        arguments:
            queueAliases: %rs_queue.queues%

    rs_queue.service:
        abstract: true
        arguments:
            eventDispatcher: "@event_dispatcher"
            redis: "@rs_queue.redis"
            queueNamesResolver: "@rs_queue.resolver.queue_alias"
            serializer: "@rs_queue.serializer"

    rs_queue.consumer:
        class: Mmoreram\RSQueueBundle\Services\Consumer
        parent: rs_queue.service

    rs_queue.producer:
        class: Mmoreram\RSQueueBundle\Services\Producer
        parent: rs_queue.service

    rs_queue.publisher:
        class: Mmoreram\RSQueueBundle\Services\Publisher
        parent: rs_queue.service

