services:

    rs_queue.resolver.queue_alias:
        class: RSQueue\Resolver\QueueAliasResolver
        arguments:
            - "%rs_queue.queues%"

    rs_queue.service:
        abstract: true
        arguments:
            - "@event_dispatcher"
            - "@rs_queue.redis"
            - "@rs_queue.resolver.queue_alias"
            - "@rs_queue.serializer"

    rs_queue.consumer:
        class: RSQueue\Services\Consumer
        parent: rs_queue.service
        public: true

    rs_queue.producer:
        class: RSQueue\Services\Producer
        parent: rs_queue.service
        public: true

    rs_queue.publisher:
        class: RSQueue\Services\Publisher
        parent: rs_queue.service
        public: true